# Generated by Django 3.2.9 on 2023-01-11 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id'], 'verbose_name': ' Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
